---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: 'test/integration/data_bags'
    roles_path: 'test/integration/roles'
    run_list:
      - recipe[apt]
      - role[incident-bot]
    attributes:
